name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.1]
    steps:
      
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: List of files inside models folder before running docker script
        run:
          ls -lh models

      - name: Run pytest to run the flash based tests
        run:
          pytest ./api/test_app.py 

      - name: List of files inside models folder after running docker script
        run:
          ls -lh models    