name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.1]
    steps:
      
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run:
          pip3 install --no-cache-dir -r requirements.txt

      - name: Run pytest to run the flash based tests
        run:
          pytest test_utils.py     

      